# TravisCI configuration for GraphQLAPI/graphql-api-for-wp
language: php
os:
  - linux
dist: bionic

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
  - 7.4

jobs:
  include:
    - name: "PHPCS"
      script:
        - vendor/bin/phpcs -n --standard=PSR2 src/
      after_script: skip

    - name: "PHPStan"
      script:
        - vendor/bin/phpstan analyse src/
      after_script: skip

    - name: "PHP 7.1"
      install:
        - travis_retry composer update --no-interaction --prefer-dist
        - vendor/bin/rector process
        - phpenv local 7.1
        - php --version
        - vendor/bin/phpstan analyse src/
      after_script: skip

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - leo@getpop.org
    on_success: change
    on_failure: always
