services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    Leoloso\GraphQLByPoPWPPlugin\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true
