services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    Leoloso\GraphQLByPoPWPPlugin\Admin\Menus\:
        resource: '../src/Admin/Menus/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\Admin\EndpointResolvers\:
        resource: '../src/Admin/EndpointResolvers/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\Admin\Development\:
        resource: '../src/Admin/Development/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\Taxonomies\:
        resource: '../src/Taxonomies/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\PostTypes\:
        resource: '../src/PostTypes/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\EditorScripts\:
        resource: '../src/EditorScripts/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\Blocks\:
        resource: '../src/Blocks/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\BlockCategories\:
        resource: '../src/BlockCategories/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    Leoloso\GraphQLByPoPWPPlugin\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true
