services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    GraphQLAPI\GraphQLAPI\Admin\Menus\:
        resource: '../src/Admin/Menus/*'
        public: true

    GraphQLAPI\GraphQLAPI\Admin\EndpointResolvers\:
        resource: '../src/Admin/EndpointResolvers/*'
        public: true

    GraphQLAPI\GraphQLAPI\Taxonomies\:
        resource: '../src/Taxonomies/*'
        public: true

    GraphQLAPI\GraphQLAPI\PostTypes\:
        resource: '../src/PostTypes/*'
        public: true

    GraphQLAPI\GraphQLAPI\EditorScripts\:
        resource: '../src/EditorScripts/*'
        public: true

    GraphQLAPI\GraphQLAPI\Blocks\:
        resource: '../src/Blocks/*'
        public: true

    GraphQLAPI\GraphQLAPI\BlockCategories\:
        resource: '../src/BlockCategories/*'
        public: true

    GraphQLAPI\GraphQLAPI\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    GraphQLAPI\GraphQLAPI\Clients\:
        resource: '../src/Clients/*'
        public: true

    markdown_content_parser:
        class: '\GraphQLAPI\GraphQLAPI\ContentProcessors\MarkdownContentParser'
        public: true
