services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    GraphQLAPI\GraphQLAPI\Admin\Menus\:
        resource: '../src/Admin/Menus/*'
        public: true

    GraphQLAPI\GraphQLAPI\Admin\EndpointResolvers\:
        resource: '../src/Admin/EndpointResolvers/*'
        public: true

    GraphQLAPI\GraphQLAPI\Admin\Development\:
        resource: '../src/Admin/Development/*'
        public: true

    GraphQLAPI\GraphQLAPI\Taxonomies\:
        resource: '../src/Taxonomies/*'
        public: true

    GraphQLAPI\GraphQLAPI\PostTypes\:
        resource: '../src/PostTypes/*'
        public: true

    GraphQLAPI\GraphQLAPI\EditorScripts\:
        resource: '../src/EditorScripts/*'
        public: true

    GraphQLAPI\GraphQLAPI\Blocks\:
        resource: '../src/Blocks/*'
        public: true

    GraphQLAPI\GraphQLAPI\BlockCategories\:
        resource: '../src/BlockCategories/*'
        public: true

    GraphQLAPI\GraphQLAPI\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    # GraphQLAPI\GraphQLAPI\ModuleResolvers\:
    #     resource: '../src/ModuleResolvers/*'
    #     public: true
